// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/configtx.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ConfigEnvelope is designed to contain _all_ configuration for a chain with no dependency
// on previous configuration transactions.
//
// It is generated with the following scheme:
//   1. Retrieve the existing configuration
//   2. Note the config properties (ConfigValue, ConfigPolicy, ConfigGroup) to be modified
//   3. Add any intermediate ConfigGroups to the ConfigUpdate.read_set (sparsely)
//   4. Add any additional desired dependencies to ConfigUpdate.read_set (sparsely)
//   5. Modify the config properties, incrementing each version by 1, set them in the ConfigUpdate.write_set
//      Note: any element not modified but specified should already be in the read_set, so may be specified sparsely
//   6. Create ConfigUpdate message and marshal it into ConfigUpdateEnvelope.update and encode the required signatures
//     a) Each signature is of type ConfigSignature
//     b) The ConfigSignature signature is over the concatenation of signature_header and the ConfigUpdate bytes (which includes a ChainHeader)
//   5. Submit new Config for ordering in Envelope signed by submitter
//     a) The Envelope Payload has data set to the marshaled ConfigEnvelope
//     b) The Envelope Payload has a header of type Header.Type.CONFIG_UPDATE
//
// The configuration manager will verify:
//   1. All items in the read_set exist at the read versions
//   2. All items in the write_set at a different version than, or not in, the read_set have been appropriately signed according to their mod_policy
//   3. The new configuration satisfies the ConfigSchema
type ConfigEnvelope struct {
	Config     *Config   `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	LastUpdate *Envelope `protobuf:"bytes,2,opt,name=last_update,json=lastUpdate" json:"last_update,omitempty"`
}

func (m *ConfigEnvelope) Reset()                    { *m = ConfigEnvelope{} }
func (m *ConfigEnvelope) String() string            { return proto.CompactTextString(m) }
func (*ConfigEnvelope) ProtoMessage()               {}
func (*ConfigEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ConfigEnvelope) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ConfigEnvelope) GetLastUpdate() *Envelope {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

type ConfigGroupSchema struct {
	Groups   map[string]*ConfigGroupSchema  `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Values   map[string]*ConfigValueSchema  `protobuf:"bytes,2,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Policies map[string]*ConfigPolicySchema `protobuf:"bytes,3,rep,name=policies" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ConfigGroupSchema) Reset()                    { *m = ConfigGroupSchema{} }
func (m *ConfigGroupSchema) String() string            { return proto.CompactTextString(m) }
func (*ConfigGroupSchema) ProtoMessage()               {}
func (*ConfigGroupSchema) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ConfigGroupSchema) GetGroups() map[string]*ConfigGroupSchema {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ConfigGroupSchema) GetValues() map[string]*ConfigValueSchema {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ConfigGroupSchema) GetPolicies() map[string]*ConfigPolicySchema {
	if m != nil {
		return m.Policies
	}
	return nil
}

type ConfigValueSchema struct {
}

func (m *ConfigValueSchema) Reset()                    { *m = ConfigValueSchema{} }
func (m *ConfigValueSchema) String() string            { return proto.CompactTextString(m) }
func (*ConfigValueSchema) ProtoMessage()               {}
func (*ConfigValueSchema) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ConfigPolicySchema struct {
}

func (m *ConfigPolicySchema) Reset()                    { *m = ConfigPolicySchema{} }
func (m *ConfigPolicySchema) String() string            { return proto.CompactTextString(m) }
func (*ConfigPolicySchema) ProtoMessage()               {}
func (*ConfigPolicySchema) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// Config represents the config for a particular channel
type Config struct {
	Sequence     uint64       `protobuf:"varint,1,opt,name=sequence" json:"sequence,omitempty"`
	ChannelGroup *ConfigGroup `protobuf:"bytes,2,opt,name=channel_group,json=channelGroup" json:"channel_group,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Config) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Config) GetChannelGroup() *ConfigGroup {
	if m != nil {
		return m.ChannelGroup
	}
	return nil
}

type ConfigUpdateEnvelope struct {
	ConfigUpdate []byte             `protobuf:"bytes,1,opt,name=config_update,json=configUpdate,proto3" json:"config_update,omitempty"`
	Signatures   []*ConfigSignature `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *ConfigUpdateEnvelope) Reset()                    { *m = ConfigUpdateEnvelope{} }
func (m *ConfigUpdateEnvelope) String() string            { return proto.CompactTextString(m) }
func (*ConfigUpdateEnvelope) ProtoMessage()               {}
func (*ConfigUpdateEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ConfigUpdateEnvelope) GetConfigUpdate() []byte {
	if m != nil {
		return m.ConfigUpdate
	}
	return nil
}

func (m *ConfigUpdateEnvelope) GetSignatures() []*ConfigSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// ConfigUpdate is used to submit a subset of config and to have the orderer apply to Config
// it is always submitted inside a ConfigUpdateEnvelope which allows the addition of signatures
// resulting in a new total configuration.  The update is applied as follows:
// 1. The versions from all of the elements in the read_set is verified against the versions in the existing config.
//    If there is a mismatch in the read versions, then the config update fails and is rejected.
// 2. Any elements in the write_set with the same version as the read_set are ignored.
// 3. The corresponding mod_policy for every remaining element in the write_set is collected.
// 4. Each policy is checked against the signatures from the ConfigUpdateEnvelope, any failing to verify are rejected
// 5. The write_set is applied to the Config and the ConfigGroupSchema verifies that the updates were legal
type ConfigUpdate struct {
	ChannelId string       `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ReadSet   *ConfigGroup `protobuf:"bytes,2,opt,name=read_set,json=readSet" json:"read_set,omitempty"`
	WriteSet  *ConfigGroup `protobuf:"bytes,3,opt,name=write_set,json=writeSet" json:"write_set,omitempty"`
}

func (m *ConfigUpdate) Reset()                    { *m = ConfigUpdate{} }
func (m *ConfigUpdate) String() string            { return proto.CompactTextString(m) }
func (*ConfigUpdate) ProtoMessage()               {}
func (*ConfigUpdate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ConfigUpdate) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ConfigUpdate) GetReadSet() *ConfigGroup {
	if m != nil {
		return m.ReadSet
	}
	return nil
}

func (m *ConfigUpdate) GetWriteSet() *ConfigGroup {
	if m != nil {
		return m.WriteSet
	}
	return nil
}

// ConfigGroup is the hierarchical data structure for holding config
type ConfigGroup struct {
	Version   uint64                   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Groups    map[string]*ConfigGroup  `protobuf:"bytes,2,rep,name=groups" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Values    map[string]*ConfigValue  `protobuf:"bytes,3,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Policies  map[string]*ConfigPolicy `protobuf:"bytes,4,rep,name=policies" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ModPolicy string                   `protobuf:"bytes,5,opt,name=mod_policy,json=modPolicy" json:"mod_policy,omitempty"`
}

func (m *ConfigGroup) Reset()                    { *m = ConfigGroup{} }
func (m *ConfigGroup) String() string            { return proto.CompactTextString(m) }
func (*ConfigGroup) ProtoMessage()               {}
func (*ConfigGroup) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ConfigGroup) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigGroup) GetGroups() map[string]*ConfigGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ConfigGroup) GetValues() map[string]*ConfigValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ConfigGroup) GetPolicies() map[string]*ConfigPolicy {
	if m != nil {
		return m.Policies
	}
	return nil
}

func (m *ConfigGroup) GetModPolicy() string {
	if m != nil {
		return m.ModPolicy
	}
	return ""
}

// ConfigValue represents an individual piece of config data
type ConfigValue struct {
	Version   uint64 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ModPolicy string `protobuf:"bytes,3,opt,name=mod_policy,json=modPolicy" json:"mod_policy,omitempty"`
}

func (m *ConfigValue) Reset()                    { *m = ConfigValue{} }
func (m *ConfigValue) String() string            { return proto.CompactTextString(m) }
func (*ConfigValue) ProtoMessage()               {}
func (*ConfigValue) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ConfigValue) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ConfigValue) GetModPolicy() string {
	if m != nil {
		return m.ModPolicy
	}
	return ""
}

type ConfigPolicy struct {
	Version   uint64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Policy    *Policy `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	ModPolicy string  `protobuf:"bytes,3,opt,name=mod_policy,json=modPolicy" json:"mod_policy,omitempty"`
}

func (m *ConfigPolicy) Reset()                    { *m = ConfigPolicy{} }
func (m *ConfigPolicy) String() string            { return proto.CompactTextString(m) }
func (*ConfigPolicy) ProtoMessage()               {}
func (*ConfigPolicy) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ConfigPolicy) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigPolicy) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *ConfigPolicy) GetModPolicy() string {
	if m != nil {
		return m.ModPolicy
	}
	return ""
}

type ConfigSignature struct {
	SignatureHeader []byte `protobuf:"bytes,1,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	Signature       []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *ConfigSignature) Reset()                    { *m = ConfigSignature{} }
func (m *ConfigSignature) String() string            { return proto.CompactTextString(m) }
func (*ConfigSignature) ProtoMessage()               {}
func (*ConfigSignature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ConfigSignature) GetSignatureHeader() []byte {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

func (m *ConfigSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigEnvelope)(nil), "common.ConfigEnvelope")
	proto.RegisterType((*ConfigGroupSchema)(nil), "common.ConfigGroupSchema")
	proto.RegisterType((*ConfigValueSchema)(nil), "common.ConfigValueSchema")
	proto.RegisterType((*ConfigPolicySchema)(nil), "common.ConfigPolicySchema")
	proto.RegisterType((*Config)(nil), "common.Config")
	proto.RegisterType((*ConfigUpdateEnvelope)(nil), "common.ConfigUpdateEnvelope")
	proto.RegisterType((*ConfigUpdate)(nil), "common.ConfigUpdate")
	proto.RegisterType((*ConfigGroup)(nil), "common.ConfigGroup")
	proto.RegisterType((*ConfigValue)(nil), "common.ConfigValue")
	proto.RegisterType((*ConfigPolicy)(nil), "common.ConfigPolicy")
	proto.RegisterType((*ConfigSignature)(nil), "common.ConfigSignature")
}

func init() { proto.RegisterFile("common/configtx.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x55, 0xe2, 0xd6, 0x4d, 0x26, 0xe9, 0xcf, 0xb7, 0xcd, 0x27, 0x8c, 0x05, 0xa2, 0x18, 0x28,
	0x2d, 0x17, 0x4e, 0x29, 0x17, 0xad, 0x90, 0x7a, 0x43, 0x55, 0x01, 0x37, 0x15, 0x75, 0xf8, 0x91,
	0x2a, 0x44, 0xe4, 0xda, 0x5b, 0xdb, 0xaa, 0xe3, 0x35, 0xeb, 0x75, 0x4b, 0x9e, 0x82, 0x07, 0xe4,
	0x0d, 0x78, 0x0a, 0xe4, 0xdd, 0xb5, 0x59, 0xb7, 0x4e, 0x22, 0xae, 0x92, 0x99, 0x39, 0xe7, 0xcc,
	0xee, 0xec, 0x1c, 0x19, 0xfe, 0xf7, 0xc8, 0x64, 0x42, 0x92, 0xa1, 0x47, 0x92, 0xcb, 0x28, 0x60,
	0x3f, 0xec, 0x94, 0x12, 0x46, 0x90, 0x2e, 0xd2, 0xe6, 0x66, 0x55, 0x2e, 0x7e, 0x44, 0xd1, 0x2c,
	0x39, 0x29, 0x89, 0x23, 0x2f, 0xc2, 0x99, 0x48, 0x5b, 0x57, 0xb0, 0x76, 0xcc, 0x55, 0x4e, 0x92,
	0x6b, 0x1c, 0x93, 0x14, 0xa3, 0x6d, 0xd0, 0x85, 0xae, 0xd1, 0xda, 0x6a, 0xed, 0xf4, 0xf6, 0xd7,
	0x6c, 0xa9, 0x23, 0x70, 0x8e, 0xac, 0xa2, 0x97, 0xd0, 0x8b, 0xdd, 0x8c, 0x8d, 0xf3, 0xd4, 0x77,
	0x19, 0x36, 0xda, 0x1c, 0xbc, 0x51, 0x82, 0x4b, 0x39, 0x07, 0x0a, 0xd0, 0x27, 0x8e, 0xb1, 0x7e,
	0x69, 0xf0, 0x9f, 0x50, 0x79, 0x4b, 0x49, 0x9e, 0x8e, 0xbc, 0x10, 0x4f, 0x5c, 0x74, 0x04, 0x7a,
	0x50, 0x84, 0x99, 0xd1, 0xda, 0xd2, 0x76, 0x7a, 0xfb, 0xcf, 0xea, 0x0d, 0x15, 0xa8, 0xcd, 0xff,
	0x67, 0x27, 0x09, 0xa3, 0x53, 0x47, 0x92, 0x0a, 0xfa, 0xb5, 0x1b, 0xe7, 0x38, 0x33, 0xda, 0x8b,
	0xe8, 0x9f, 0x39, 0x4e, 0xd2, 0x05, 0x09, 0x1d, 0x43, 0xa7, 0x1c, 0x89, 0xa1, 0x71, 0x81, 0xe7,
	0xb3, 0x05, 0x3e, 0x48, 0xa4, 0x90, 0xa8, 0x88, 0xe6, 0x47, 0xe8, 0x29, 0x47, 0x43, 0x1b, 0xa0,
	0x5d, 0xe1, 0x29, 0x9f, 0x5f, 0xd7, 0x29, 0xfe, 0xa2, 0x21, 0x2c, 0xf3, 0x7e, 0x72, 0x4c, 0xf7,
	0x67, 0xb6, 0x70, 0x04, 0xee, 0x75, 0xfb, 0xb0, 0x55, 0xa8, 0x2a, 0x27, 0xfe, 0x67, 0x55, 0xce,
	0xbd, 0xab, 0xfa, 0x05, 0x56, 0x6b, 0xd7, 0x68, 0xd0, 0xdd, 0xab, 0xeb, 0x9a, 0x75, 0x5d, 0xce,
	0x9e, 0xde, 0x11, 0xb6, 0x36, 0xcb, 0xc7, 0x55, 0x1a, 0x5b, 0x03, 0x40, 0x77, 0x59, 0xd6, 0x37,
	0xd0, 0x45, 0x16, 0x99, 0xd0, 0xc9, 0xf0, 0xf7, 0x1c, 0x27, 0x1e, 0xe6, 0x27, 0x58, 0x72, 0xaa,
	0x18, 0x1d, 0xc2, 0xaa, 0x17, 0xba, 0x49, 0x82, 0xe3, 0x31, 0x7f, 0x6b, 0x79, 0x9c, 0xcd, 0x86,
	0xe1, 0x39, 0x7d, 0x89, 0xe4, 0x91, 0xc5, 0x60, 0x20, 0x8a, 0x62, 0xf1, 0xaa, 0xdd, 0x7e, 0x02,
	0xab, 0x62, 0x7b, 0xcb, 0xad, 0x2d, 0x5a, 0xf6, 0x9d, 0xbe, 0xa7, 0x80, 0xd1, 0x01, 0x40, 0x16,
	0x05, 0x89, 0xcb, 0x72, 0x5a, 0x2d, 0xd5, 0xbd, 0x7a, 0xcf, 0x51, 0x59, 0x77, 0x14, 0xa8, 0xf5,
	0xb3, 0x05, 0x7d, 0xb5, 0x2d, 0x7a, 0x08, 0x50, 0x5e, 0x20, 0xf2, 0xe5, 0x80, 0xbb, 0x32, 0xf3,
	0xde, 0x47, 0x36, 0x74, 0x28, 0x76, 0xfd, 0x71, 0x86, 0xd9, 0xbc, 0xab, 0xad, 0x14, 0xa0, 0x11,
	0x66, 0x68, 0x0f, 0xba, 0x37, 0x34, 0x62, 0x98, 0x13, 0xb4, 0xd9, 0x84, 0x0e, 0x47, 0x8d, 0x30,
	0xb3, 0x7e, 0x6b, 0xd0, 0x53, 0x2a, 0xc8, 0x80, 0x95, 0x6b, 0x4c, 0xb3, 0x88, 0x24, 0x72, 0xd8,
	0x65, 0x88, 0x0e, 0x2a, 0x13, 0x8a, 0x0b, 0x3f, 0x6a, 0x10, 0x6e, 0xb4, 0xdf, 0x41, 0x65, 0x3f,
	0x6d, 0x36, 0xb1, 0xc9, 0x78, 0x47, 0x8a, 0xf1, 0x96, 0x38, 0xf5, 0x71, 0x13, 0x75, 0x86, 0xe5,
	0x8a, 0xd9, 0x4e, 0x88, 0x3f, 0xe6, 0xf1, 0xd4, 0x58, 0x16, 0xb3, 0x9d, 0x10, 0x5f, 0xec, 0x99,
	0x79, 0xba, 0xc8, 0x91, 0xbb, 0xf5, 0x1d, 0x6f, 0x1c, 0xa4, 0xe2, 0x9a, 0xd3, 0x45, 0x5e, 0x9c,
	0xaf, 0xc7, 0xb9, 0xaa, 0xde, 0xd9, 0x62, 0x17, 0xbe, 0xa8, 0x2b, 0x0e, 0x9a, 0x5c, 0xa8, 0xfa,
	0xef, 0x6b, 0xf9, 0xd6, 0xbc, 0xd9, 0x9c, 0xb7, 0x1e, 0xa8, 0xc2, 0x7d, 0x29, 0x71, 0x6b, 0xa0,
	0xda, 0xad, 0x81, 0x5a, 0xa4, 0xdc, 0x6d, 0x11, 0xcf, 0x91, 0xdf, 0x06, 0x5d, 0x8a, 0xb4, 0xeb,
	0x1f, 0x10, 0x79, 0x64, 0x59, 0x5d, 0xd4, 0xf0, 0x1c, 0xd6, 0x6f, 0x99, 0x0d, 0xed, 0xc2, 0x46,
	0x65, 0xb7, 0x71, 0x88, 0x5d, 0x1f, 0x53, 0xe9, 0xe0, 0xf5, 0x2a, 0xff, 0x8e, 0xa7, 0xd1, 0x03,
	0xe8, 0x56, 0x29, 0x79, 0xcf, 0xbf, 0x89, 0x37, 0x67, 0xf0, 0x94, 0xd0, 0xc0, 0x0e, 0xa7, 0x29,
	0xa6, 0x31, 0xf6, 0x03, 0x4c, 0xed, 0x4b, 0xf7, 0x82, 0x46, 0x9e, 0xf8, 0x2a, 0x66, 0xf2, 0xc4,
	0xe7, 0xbb, 0x41, 0xc4, 0xc2, 0xfc, 0xa2, 0x08, 0x87, 0x37, 0xa1, 0xcb, 0xa2, 0x8c, 0x90, 0x74,
	0x28, 0xa0, 0x43, 0x01, 0x95, 0x5f, 0xd9, 0x0b, 0x9d, 0x87, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xcd, 0x05, 0x0a, 0x5b, 0x9c, 0x07, 0x00, 0x00,
}
