// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/peer.proto

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PeerID struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PeerID) Reset()                    { *m = PeerID{} }
func (m *PeerID) String() string            { return proto.CompactTextString(m) }
func (*PeerID) ProtoMessage()               {}
func (*PeerID) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *PeerID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PeerEndpoint struct {
	Id      *PeerID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address string  `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *PeerEndpoint) Reset()                    { *m = PeerEndpoint{} }
func (m *PeerEndpoint) String() string            { return proto.CompactTextString(m) }
func (*PeerEndpoint) ProtoMessage()               {}
func (*PeerEndpoint) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *PeerEndpoint) GetId() *PeerID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PeerEndpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*PeerID)(nil), "protos.PeerID")
	proto.RegisterType((*PeerEndpoint)(nil), "protos.PeerEndpoint")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Endorser service

type EndorserClient interface {
	ProcessProposal(ctx context.Context, in *SignedProposal, opts ...grpc.CallOption) (*ProposalResponse, error)
}

type endorserClient struct {
	cc *grpc.ClientConn
}

func NewEndorserClient(cc *grpc.ClientConn) EndorserClient {
	return &endorserClient{cc}
}

func (c *endorserClient) ProcessProposal(ctx context.Context, in *SignedProposal, opts ...grpc.CallOption) (*ProposalResponse, error) {
	out := new(ProposalResponse)
	err := grpc.Invoke(ctx, "/protos.Endorser/ProcessProposal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Endorser service

type EndorserServer interface {
	ProcessProposal(context.Context, *SignedProposal) (*ProposalResponse, error)
}

func RegisterEndorserServer(s *grpc.Server, srv EndorserServer) {
	s.RegisterService(&_Endorser_serviceDesc, srv)
}

func _Endorser_ProcessProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndorserServer).ProcessProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Endorser/ProcessProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndorserServer).ProcessProposal(ctx, req.(*SignedProposal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Endorser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Endorser",
	HandlerType: (*EndorserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessProposal",
			Handler:    _Endorser_ProcessProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peer/peer.proto",
}

func init() { proto.RegisterFile("peer/peer.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xdd, 0x22, 0xab, 0x46, 0x71, 0x21, 0x82, 0x94, 0xb2, 0x88, 0xf4, 0xa2, 0xa7, 0x14,
	0xd6, 0x6f, 0x20, 0x16, 0xf4, 0x20, 0xd4, 0x7a, 0xf3, 0x22, 0x69, 0x33, 0xb6, 0x81, 0x6d, 0x26,
	0xcc, 0x54, 0xc4, 0x6f, 0x2f, 0x4d, 0x5a, 0x61, 0x2f, 0xf9, 0xf3, 0x7e, 0x6f, 0x5e, 0x26, 0x23,
	0x36, 0x1e, 0x80, 0x8a, 0x69, 0x51, 0x9e, 0x70, 0x44, 0xb9, 0x0e, 0x1b, 0x67, 0x57, 0x11, 0x10,
	0x7a, 0x64, 0xbd, 0x8f, 0x30, 0xdb, 0x1e, 0x88, 0x9f, 0x04, 0xec, 0xd1, 0x31, 0x44, 0x9a, 0x6f,
	0xc5, 0xba, 0x02, 0xa0, 0x97, 0x27, 0x29, 0xc5, 0xb1, 0xd3, 0x03, 0xa4, 0xab, 0xdb, 0xd5, 0xfd,
	0x59, 0x1d, 0xce, 0xf9, 0xb3, 0xb8, 0x98, 0x68, 0xe9, 0x8c, 0x47, 0xeb, 0x46, 0x79, 0x23, 0x12,
	0x6b, 0x82, 0xe3, 0x7c, 0x77, 0x19, 0x13, 0x58, 0xc5, 0xfa, 0x3a, 0xb1, 0x46, 0xa6, 0xe2, 0x44,
	0x1b, 0x43, 0xc0, 0x9c, 0x26, 0x21, 0x66, 0xb9, 0xee, 0xde, 0xc4, 0x69, 0xe9, 0x0c, 0x12, 0x03,
	0xc9, 0x52, 0x6c, 0x2a, 0xc2, 0x16, 0x98, 0xab, 0xb9, 0x2b, 0x79, 0xbd, 0x84, 0xbd, 0xdb, 0xce,
	0x81, 0x59, 0xf4, 0x2c, 0xfd, 0x7f, 0x64, 0x56, 0xea, 0xb9, 0xfd, 0xfc, 0xe8, 0xf1, 0x55, 0xe4,
	0x48, 0x9d, 0xea, 0x7f, 0x3d, 0xd0, 0x1e, 0x4c, 0x07, 0xa4, 0xbe, 0x74, 0x43, 0xb6, 0x5d, 0x6a,
	0xa6, 0x8f, 0x7f, 0xdc, 0x75, 0x76, 0xec, 0xbf, 0x1b, 0xd5, 0xe2, 0x50, 0xfc, 0xf4, 0x7a, 0xb4,
	0x8c, 0xe8, 0x8b, 0x68, 0x2c, 0xa2, 0x31, 0x8c, 0xb2, 0x89, 0x43, 0x7c, 0xf8, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x9b, 0x18, 0x50, 0xbb, 0x5e, 0x01, 0x00, 0x00,
}
