// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/rwset/rwset.proto

/*
Package rwset is a generated protocol buffer package.

It is generated from these files:
	ledger/rwset/rwset.proto

It has these top-level messages:
	TxReadWriteSet
	NsReadWriteSet
*/
package rwset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxReadWriteSet_DataModel int32

const (
	TxReadWriteSet_KV TxReadWriteSet_DataModel = 0
)

var TxReadWriteSet_DataModel_name = map[int32]string{
	0: "KV",
}
var TxReadWriteSet_DataModel_value = map[string]int32{
	"KV": 0,
}

func (x TxReadWriteSet_DataModel) String() string {
	return proto.EnumName(TxReadWriteSet_DataModel_name, int32(x))
}
func (TxReadWriteSet_DataModel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// TxReadWriteSet encapsulates a read-write set for a transaction
// DataModel specifies the enum value of the data model
// ns_rwset field specifies a list of chaincode specific read-write set (one for each chaincode)
type TxReadWriteSet struct {
	DataModel TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsRwset   []*NsReadWriteSet        `protobuf:"bytes,2,rep,name=ns_rwset,json=nsRwset" json:"ns_rwset,omitempty"`
}

func (m *TxReadWriteSet) Reset()                    { *m = TxReadWriteSet{} }
func (m *TxReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*TxReadWriteSet) ProtoMessage()               {}
func (*TxReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TxReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if m != nil {
		return m.DataModel
	}
	return TxReadWriteSet_KV
}

func (m *TxReadWriteSet) GetNsRwset() []*NsReadWriteSet {
	if m != nil {
		return m.NsRwset
	}
	return nil
}

// NsReadWriteSet encapsulates the read-write set for a chaincode
type NsReadWriteSet struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Rwset     []byte `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"`
}

func (m *NsReadWriteSet) Reset()                    { *m = NsReadWriteSet{} }
func (m *NsReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*NsReadWriteSet) ProtoMessage()               {}
func (*NsReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NsReadWriteSet) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NsReadWriteSet) GetRwset() []byte {
	if m != nil {
		return m.Rwset
	}
	return nil
}

func init() {
	proto.RegisterType((*TxReadWriteSet)(nil), "rwset.TxReadWriteSet")
	proto.RegisterType((*NsReadWriteSet)(nil), "rwset.NsReadWriteSet")
	proto.RegisterEnum("rwset.TxReadWriteSet_DataModel", TxReadWriteSet_DataModel_name, TxReadWriteSet_DataModel_value)
}

func init() { proto.RegisterFile("ledger/rwset/rwset.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xed, 0x64, 0xd3, 0x3e, 0xa5, 0x48, 0x54, 0xe8, 0x41, 0x70, 0xec, 0x54, 0x3c, 0x24,
	0x32, 0xef, 0x1e, 0x64, 0x37, 0xd1, 0x43, 0x14, 0x05, 0x41, 0xc6, 0x6b, 0xf3, 0x6c, 0x0b, 0x6b,
	0x13, 0x92, 0xc8, 0xf4, 0x93, 0xf8, 0x75, 0xc5, 0x64, 0x73, 0xdb, 0x25, 0xe4, 0xfd, 0xf9, 0xfd,
	0x92, 0xc7, 0x1f, 0xf2, 0x05, 0xa9, 0x9a, 0xac, 0xb0, 0x4b, 0x47, 0x3e, 0x9e, 0xdc, 0x58, 0xed,
	0x35, 0x1b, 0x86, 0x61, 0xf2, 0x93, 0x40, 0xf6, 0xfc, 0x25, 0x09, 0xd5, 0xab, 0x6d, 0x3d, 0x3d,
	0x91, 0x67, 0xb7, 0x00, 0x0a, 0x3d, 0xce, 0x3b, 0xad, 0x68, 0x91, 0x27, 0xe3, 0xa4, 0xc8, 0xa6,
	0x97, 0x3c, 0xba, 0xbb, 0x28, 0x9f, 0xa1, 0xc7, 0x87, 0x3f, 0x4c, 0xa6, 0x6a, 0x7d, 0x65, 0xd7,
	0x70, 0xd8, 0xbb, 0x79, 0xe0, 0xf3, 0xc1, 0x78, 0xbf, 0x38, 0x9a, 0x9e, 0xaf, 0xec, 0x47, 0xb7,
	0x6d, 0xcb, 0x83, 0xde, 0xc9, 0xb0, 0xc4, 0x29, 0xa4, 0xff, 0x2f, 0xb1, 0x11, 0x0c, 0xee, 0x5f,
	0x4e, 0xf6, 0x26, 0x33, 0xc8, 0x76, 0x79, 0x76, 0x01, 0x69, 0x8f, 0x1d, 0x39, 0x83, 0x15, 0x85,
	0xbd, 0x52, 0xb9, 0x09, 0xd8, 0x19, 0x0c, 0xd7, 0x7f, 0x26, 0xc5, 0xb1, 0x8c, 0xc3, 0xdd, 0x3b,
	0x5c, 0x69, 0x5b, 0xf3, 0xe6, 0xdb, 0x90, 0x8d, 0x5d, 0xf0, 0x0f, 0x2c, 0x6d, 0x5b, 0xc5, 0x1a,
	0x1c, 0x5f, 0x85, 0x81, 0x7e, 0x13, 0x75, 0xeb, 0x9b, 0xcf, 0x92, 0x57, 0xba, 0x13, 0xcb, 0x06,
	0x7d, 0xeb, 0xb4, 0x36, 0x22, 0x0a, 0x22, 0x0a, 0x62, 0xbb, 0xd1, 0x72, 0x14, 0xc2, 0x9b, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xca, 0xd7, 0x2e, 0x68, 0x01, 0x00, 0x00,
}
